server:
  port: 9377

spring:
  datasource:
    name: tingjian
    # url: jdbc:mysql://127.0.0.1:3306/tingjian?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/tingjian?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true
    username: xiesu
    password: xiesu123456
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true




  #
  ## the jpa-configure
  #  spring.jpa.database=MYSQL
  #  spring.jpa.hibernate.ddl-auto=none
  #  spring.jpa.show-sql=true
  #  spring.jackson.serialization.indent_output=true
  #  spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #  #request-configure
  #  spring.http.multipart.maxFileSize=100Mb
  #  spring.http.multipart.maxRequestSize=100Mb
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  #    properties:
  #      hibernate:
  #        hbm2ddl:
  #          auto: update


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB